### ISSUE TITLE
mapmaker.jl gives strange results

### ISSUE THREAD

**Issue by silviacaprioli** [lspestrip/stripeline2#3]
I tried to run `mapmaker.jl` on a TOD built from the 44 GHz sky map of Planck by using the scanning strategy of STRIP.  The TOD also includes simulated baselines of 1/f noise. 
I made the code print the content of some pixels (from 193706 to 193716) of the Planck map in input and the same pixels of the destriped map. 
That is the result:

Planck map:   [-0.000203848, -0.000209665, -0.000218049, -0.000210582, -0.00017884, -0.000142592, -0.000123256, -0.00011911, -0.000123725, -0.000137174, -0.000149694]

destriped map: [0.00218755, 0.00278706, 0.00267588, 0.00271644, 0.00329075, 0.00260661, 0.00298804, 0.00232408, 0.00213763, 0.00278141, 0.00205138]

By changing the definition of `binned_map` in function `tod2map` from  `binned_map= Array{Float64}(num_of_pixels)` to `binned_map = zeros(Float64, num_of_pixels)`  everything works properly: 

Planck map: [-0.000203848, -0.000209665, -0.000218049, -0.000210582, -0.00017884, -0.000142592, -0.000123256, -0.00011911, -0.000123725, -0.000137174, -0.000149694]

destriped map: [-0.000203846, -0.000209665, -0.000218049, -0.000210581, -0.000178841, -0.000142593, -0.000123257, -0.000119112, -0.000123726, -0.000137175, -0.000149695]

why? this is a quite strange behaviour

**Comment by ziotom78** [comment]
Thanks @silviacaprioli. May you please post a short code here that reproduces the behaviour? Otherwise people will not be able to reproduce the bug.

I bet it is not crucial that the input map is Planck 44 GHz, any map should do. You might build a very simple map whose pixels have the values 1, 2, 3…. and re-run your code, so that people will not have to download the Planck map to replicate your problem.
